'==============================================================================
'  WARNING!!  This file is overwritten by the Block UI Styler while generating
'  the automation code. Any modifications to this file will be lost after
'  generating the code again.
'
'       Filename:  C:\Users\jhmrrs\Documents\Projects\NX Plugin Tool\GUI\PatternTimeEstimator.vb
'
'        This file was generated by the NX Block UI Styler
'        Created by: jhmrrs
'              Version: NX 1980
'              Date: 04-07-2023  (Format: mm-dd-yyyy)
'              Time: 14:01 (Format: hh-mm)
'
'==============================================================================

'==============================================================================
'  Purpose:  This TEMPLATE file contains VB.NET source to guide you in the
'  construction of your Block application dialog. The generation of your
'  dialog file (.dlx extension) is the first step towards dialog construction
'  within NX.  You must now create a NX Open application that
'  utilizes this file (.dlx).
'
'  The information in this file provides you with the following:
'
'  1.  Help on how to load and display your Block UI Styler dialog in NX
'      using APIs provided in NXOpen.BlockStyler namespace
'  2.  The empty callback methods (stubs) associated with your dialog items
'      have also been placed in this file. These empty methods have been
'      created simply to start you along with your coding requirements.
'      The method name, argument list and possible return values have already
'      been provided for you.
'==============================================================================

'------------------------------------------------------------------------------
'These imports are needed for the following template code
'------------------------------------------------------------------------------
Option Strict Off
Imports System
Imports NXOpen
Imports NXOpen.BlockStyler

'------------------------------------------------------------------------------
'Represents Block Styler application class
'------------------------------------------------------------------------------
Public Class PatternTimeEstimator
    'class members
    Private Shared theSession As Session
    Private Shared theUI As UI
    Private theDlxFileName As String
    Private theDialog As NXOpen.BlockStyler.BlockDialog
    Private group0 As NXOpen.BlockStyler.Group
    Private select_type As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private num_instances As NXOpen.BlockStyler.IntegerBlock' Block type: Integer
    Private group1 As NXOpen.BlockStyler.Group' Block type: Group
    Private face_select0 As NXOpen.BlockStyler.FaceCollector' Block type: Face Collector
    Private LabelResults As NXOpen.BlockStyler.Label' Block type: Label
    Private table As NXOpen.BlockStyler.Table' Block type: TableLayout
    Private Label_FeaturePattern As NXOpen.BlockStyler.Label' Block type: Label
    Private feature_time As NXOpen.BlockStyler.Label' Block type: Label
    Private Label_FacePattern As NXOpen.BlockStyler.Label' Block type: Label
    Private face_time As NXOpen.BlockStyler.Label' Block type: Label
    Private Label_GeoPattern As NXOpen.BlockStyler.Label' Block type: Label
    Private geo_time As NXOpen.BlockStyler.Label' Block type: Label
    '------------------------------------------------------------------------------
    'Bit Option for Property: EntityType
    '------------------------------------------------------------------------------
    Public Shared ReadOnly Dim                          EntityType_AllowFaces As Integer =    16
    Public Shared ReadOnly Dim                         EntityType_AllowDatums As Integer =    32
    Public Shared ReadOnly Dim                         EntityType_AllowBodies As Integer =    64
    '------------------------------------------------------------------------------
    'Bit Option for Property: FaceRules
    '------------------------------------------------------------------------------
    Public Shared ReadOnly Dim                           FaceRules_SingleFace As Integer =     1
    Public Shared ReadOnly Dim                          FaceRules_RegionFaces As Integer =     2
    Public Shared ReadOnly Dim                         FaceRules_TangentFaces As Integer =     4
    Public Shared ReadOnly Dim                   FaceRules_TangentRegionFaces As Integer =     8
    Public Shared ReadOnly Dim                            FaceRules_BodyFaces As Integer =    16
    Public Shared ReadOnly Dim                         FaceRules_FeatureFaces As Integer =    32
    Public Shared ReadOnly Dim                        FaceRules_AdjacentFaces As Integer =    64
    Public Shared ReadOnly Dim                  FaceRules_ConnectedBlendFaces As Integer =   128
    Public Shared ReadOnly Dim                        FaceRules_AllBlendFaces As Integer =   256
    Public Shared ReadOnly Dim                             FaceRules_RibFaces As Integer =   512
    Public Shared ReadOnly Dim                            FaceRules_SlotFaces As Integer =  1024
    Public Shared ReadOnly Dim                   FaceRules_BossandPocketFaces As Integer =  2048
    Public Shared ReadOnly Dim                       FaceRules_MergedRibFaces As Integer =  4096
    Public Shared ReadOnly Dim                  FaceRules_RegionBoundaryFaces As Integer =  8192
    Public Shared ReadOnly Dim                 FaceRules_FaceandAdjacentFaces As Integer = 16384
    Public Shared ReadOnly Dim                            FaceRules_HoleFaces As Integer = 32768

    '------------------------------------------------------------------------------
    'Custom Variables
    '------------------------------------------------------------------------------
    Private obj_count       As Integer = 0
    Private feature_scale   As Double = 1
    Private face_scale      As Double = 1
    Private geo_scale       As Double = 1
    Private feature_offset  As Double = 0 
    Private face_offset     As Double = 0 
    Private geo_offset      As Double = 0   
    
#Region "Block Styler Dialog Designer generator code"
    '------------------------------------------------------------------------------
    'Constructor for NX Styler class
    '------------------------------------------------------------------------------
    Public Sub New()
        Try
        
            theSession = Session.GetSession()
            theUI = UI.GetUI()
            theDlxFileName = "PatternTimeEstimator.dlx"
            theDialog = theUI.CreateDialog(theDlxFileName)
            theDialog.AddApplyHandler(AddressOf apply_cb)
            theDialog.AddUpdateHandler(AddressOf update_cb)
            theDialog.AddInitializeHandler(AddressOf initialize_cb)
            theDialog.AddDialogShownHandler(AddressOf dialogShown_cb)
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            Throw ex
        End Try
    End Sub
#End Region
    
    '------------------------------- DIALOG LAUNCHING ---------------------------------
    '
    '    Before invoking this application one needs to open any part/empty part in NX
    '    because of the behavior of the blocks.
    '
    '    Make sure the dlx file is in one of the following locations:
    '        1.) From where NX session is launched
    '        2.) $UGII_USER_DIR/application
    '        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    '            recommended. This variable is set to a full directory path to a file 
    '            containing a list of root directories for all custom applications.
    '            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    '
    '    You can create the dialog using one of the following way:
    '
    '    1. Journal Replay
    '
    '        1) Replay this file through Tool->Journal->Play Menu.
    '
    '    2. USER EXIT
    '
    '        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    '        2) Invoke the Shared Library through File->Execute->NX Open menu.
    '
    '------------------------------------------------------------------------------
    Public Shared Sub Main()
        Dim thePatternTimeEstimator As PatternTimeEstimator = Nothing
        Try
        
            thePatternTimeEstimator = New PatternTimeEstimator()
            ' The following method shows the dialog immediately
            thePatternTimeEstimator.Show()
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        Finally
            If thePatternTimeEstimator IsNot Nothing Then 
                thePatternTimeEstimator.Dispose()
                thePatternTimeEstimator = Nothing
            End If
        End Try
    End Sub
    '------------------------------------------------------------------------------
    ' This method specifies how a shared image is unloaded from memory
    ' within NX. This method gives you the capability to unload an
    ' internal NX Open application or user  exit from NX. Specify any
    ' one of the three constants as a return value to determine the type
    ' of unload to perform:
    '
    '
    '    Immediately : unload the library as soon as the automation program has completed
    '    Explicitly  : unload the library from the "Unload Shared Image" dialog
    '    AtTermination : unload the library when the NX session terminates
    '
    '
    ' NOTE:  A program which associates NX Open applications with the menubar
    ' MUST NOT use this option since it will UNLOAD your NX Open application image
    ' from the menubar.
    '------------------------------------------------------------------------------
    Public Shared Function GetUnloadOption(ByVal arg As String) As Integer
        'Return CType(Session.LibraryUnloadOption.Explicitly, Integer)
         Return CType(Session.LibraryUnloadOption.Immediately, Integer)
        ' Return CType(Session.LibraryUnloadOption.AtTermination, Integer)
    End Function
    '------------------------------------------------------------------------------
    ' Following method cleanup any housekeeping chores that may be needed.
    ' This method is automatically called by NX.
    '------------------------------------------------------------------------------
    Public Shared Sub UnloadLibrary(ByVal arg As String)
        Try
        
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'This method shows the dialog on the screen
    '------------------------------------------------------------------------------
    Public Sub Show()
        Try
        
            theDialog.Show
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Method Name: Dispose
    '------------------------------------------------------------------------------
    Public Sub Dispose()
        If theDialog IsNot Nothing Then 
            theDialog.Dispose()
            theDialog = Nothing
        End If
    End Sub
    
    '------------------------------------------------------------------------------
    '---------------------Block UI Styler Callback Functions--------------------------
    '------------------------------------------------------------------------------
    
    '------------------------------------------------------------------------------
    'Callback Name: initialize_cb
    '------------------------------------------------------------------------------
    Public Sub initialize_cb()
        Try
        
            group0 = CType(theDialog.TopBlock.FindBlock("group0"), NXOpen.BlockStyler.Group)
            select_type = CType(theDialog.TopBlock.FindBlock("select_type"), NXOpen.BlockStyler.Enumeration)
            num_instances = CType(theDialog.TopBlock.FindBlock("num_instances"), NXOpen.BlockStyler.IntegerBlock)
            group1 = CType(theDialog.TopBlock.FindBlock("group1"), NXOpen.BlockStyler.Group)
            face_select0 = CType(theDialog.TopBlock.FindBlock("face_select0"), NXOpen.BlockStyler.FaceCollector)
            LabelResults = CType(theDialog.TopBlock.FindBlock("LabelResults"), NXOpen.BlockStyler.Label)
            table = CType(theDialog.TopBlock.FindBlock("table"), NXOpen.BlockStyler.Table)
            Label_FeaturePattern = CType(theDialog.TopBlock.FindBlock("Label_FeaturePattern"), NXOpen.BlockStyler.Label)
            feature_time = CType(theDialog.TopBlock.FindBlock("feature_time"), NXOpen.BlockStyler.Label)
            Label_FacePattern = CType(theDialog.TopBlock.FindBlock("Label_FacePattern"), NXOpen.BlockStyler.Label)
            face_time = CType(theDialog.TopBlock.FindBlock("face_time"), NXOpen.BlockStyler.Label)
            Label_GeoPattern = CType(theDialog.TopBlock.FindBlock("Label_GeoPattern"), NXOpen.BlockStyler.Label)
            geo_time = CType(theDialog.TopBlock.FindBlock("geo_time"), NXOpen.BlockStyler.Label)
            
            'Set up model
            calibrate
            updateFaceRules

        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Callback Name: dialogShown_cb
    'This callback is executed just before the dialog launch. Thus any value set 
    'here will take precedence and dialog will be launched showing that value. 
    '------------------------------------------------------------------------------
    Public Sub dialogShown_cb()
        Try
        
            '---- Enter your callback code here -----
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Callback Name: apply_cb
    '------------------------------------------------------------------------------
    Public Function apply_cb() As Integer
        Dim errorCode as Integer = 0
        Try
        
            '---- Enter your callback code here -----
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            errorCode = 1
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
        apply_cb = errorCode
    End Function
    
    '------------------------------------------------------------------------------
    'Callback Name: update_cb
    '------------------------------------------------------------------------------
    Public Function update_cb(ByVal block As NXOpen.BlockStyler.UIBlock) As Integer
        Try
        
            If block Is select_type Then
            updateFaceRules
            
            ElseIf block Is num_instances Then
            updateTimeLabels
            
            ElseIf block Is face_select0 Then
            getObjectCount
            updateTimeLabels
            
            ElseIf block Is LabelResults Then
            '---- Enter your code here -----
            
            ElseIf block Is Label_FeaturePattern Then
            '---- Enter your code here -----
            
            ElseIf block Is feature_time Then
            '---- Enter your code here -----
            
            ElseIf block Is Label_FacePattern Then
            '---- Enter your code here -----
            
            ElseIf block Is face_time Then
            '---- Enter your code here -----
            
            ElseIf block Is Label_GeoPattern Then
            '---- Enter your code here -----
            
            ElseIf block Is geo_time Then
            '---- Enter your code here -----
            
            End If
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
        update_cb = 0
    End Function
    
    '------------------------------------------------------------------------------
    'Function Name: GetBlockProperties
    'Returns the propertylist of the specified BlockID
    '------------------------------------------------------------------------------
    Public Function GetBlockProperties(ByVal blockID As String) As PropertyList
        GetBlockProperties = Nothing
        Try
        
            GetBlockProperties = theDialog.GetBlockProperties(blockID)
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: calibrate
    'Finds scaling factors for each patterning type
    '------------------------------------------------------------------------------
    Private Function calibrate(Optional debug_mode As Boolean = False)
        Try
            Dim markId1 As NXOpen.Session.UndoMarkId = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Delete")
            Dim SPACING as Decimal = 2.5
            Dim block As NXOpen.Features.Block = Nothing
            Dim slab as NXOpen.Features.Block = Nothing
            createInitialObjects(block, slab, debug_mode)

            runTests("FEATURE", block, SPACING, feature_scale, feature_offset, debug_mode)
            runTests("FACE", block, SPACING, face_scale, face_offset, debug_mode)
            runTests("GEO", block, SPACING, geo_scale, geo_offset, debug_mode)

            If Not debug_mode Then
                theSession.UpdateManager.AddToDeleteList(block)
                theSession.UpdateManager.AddToDeleteList(slab)
                theSession.UpdateManager.DoUpdate(markId1)
            End If

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: createInitialObjects
    'Creates the block that is used as the seed feature (or geometry) for all the patterns. Also
    ' creates a large block (named slab) used for joining features together.
    '------------------------------------------------------------------------------
    Private Function createInitialObjects(ByRef block As NXOpen.Features.Block, ByRef slab As NXOpen.Features.Block, Optional debug_mode As Boolean = False)
        Dim remoteness_scale As Decimal = 100
        If debug_mode Then 
            remoteness_scale = 1 
        End If
        Dim location As Decimal = -200 * remoteness_scale
        Dim by_location As Decimal = location - 0.2
        Dim remote_point as NXOpen.Point3d = New NXOpen.Point3d(location, location, location)
        Dim by_remote_point as NXOpen.Point3d = New NXOpen.Point3d(by_location, by_location, by_location)

        block = makeBlock(remote_point)
        slab = makeSlab(by_remote_point, block)
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeBlock
    'Makes a single cube
    '------------------------------------------------------------------------------
    Private Function makeBlock(center as NXOpen.Point3d, Optional length As String = "1") As NXOpen.Features.Block
        Try
            Dim workPart As NXOpen.Part = theSession.Parts.Work
            Dim builder As NXOpen.Features.BlockFeatureBuilder
            builder = workPart.Features.CreateBlockFeatureBuilder(Nothing)

            builder.SetOriginAndLengths(center, length, length, length)
            builder.BooleanOption.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create
            Dim block As NXOpen.Features.Block = builder.CommitFeature
            
            builder.Destroy
            Return block

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeSlab
    'Makes a large slab to do patterning on
    '------------------------------------------------------------------------------
    Private Function makeSlab(center as NXOpen.Point3d, block as NXOpen.Features.Block, Optional length as String = "15", Optional thickness as String = ".2") As NXOpen.Features.Block
        Try
            Dim workPart As NXOpen.Part = theSession.Parts.Work
            Dim slab_builder As NXOpen.Features.BlockFeatureBuilder
            slab_builder = workPart.Features.CreateBlockFeatureBuilder(Nothing)

            slab_builder.SetOriginAndLengths(center, length, length, thickness)
            Dim block_body_feature As NXOpen.Features.BodyFeature = CType(block, NXOpen.Features.BodyFeature)
            Dim block_bodies() As NXOpen.Body = block_body_feature.GetBodies()
            slab_builder.setBooleanOperationAndTarget(NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Unite, block_bodies(0))
            
            Dim slab As NXOpen.Features.Block = slab_builder.CommitFeature
            slab_builder.Destroy
            Return slab

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: runTests
    'Runs the calibration test for the type of pattern passed as a String and sets the associated constants.
    ' Type is an enumerated variable with values:
    ' - "FEATURE": for a feature pattern
    ' - "FACE": for a face pattern
    ' - "GEO": for a Geo pattern
    '------------------------------------------------------------------------------
    Private Function runTests(type as String, block As NXOpen.Features.Block, spacing As Decimal, ByRef scale As Double, ByRef offset As Double, Optional debug_mode As Boolean = False)
        Dim duration1 as Single, duration2 as Single
        Dim NUM_TEST1_INST As Integer = 2, NUM_TEST2_INST As Integer = 6
        Dim NUM_OBJECTS_IN_CUBE As Integer = 6 '6 faces and 12 edges in test cube
        
        runTest(type, block, 2, spacing, False) 'Eliminate feature startup bias
        duration1 = runTest(type, block, NUM_TEST1_INST, spacing, debug_mode)
        duration2 = runTest(type, block, NUM_TEST2_INST, spacing, debug_mode)

        scale = (duration2 - duration1) / (NUM_OBJECTS_IN_CUBE * (NUM_TEST2_INST - NUM_TEST1_INST))
        offset = duration1 - (scale * NUM_TEST1_INST * NUM_OBJECTS_IN_CUBE)
    End Function

    '------------------------------------------------------------------------------
    'Function Name: runTest
    'Calls the correct calibration function for the type of pattern passed as a String. Returns the duration of the test
    ' Type is an enumerated variable with values:
    ' - "FEATURE": for a feature pattern
    ' - "FACE": for a face pattern
    ' - "GEO": for a Geo pattern
    '------------------------------------------------------------------------------
    Private Function runTest(type as String, block As NxOpen.Features.Block, num_instances As Integer, spacing As Decimal, Optional debug_mode As Boolean = False) as Single
        Dim start_time as Single, duration as Single

        start_time = Timer
        If type = "FEATURE" Then
            Dim feature_pattern As NXOpen.Features.PatternFeature = makeFeaturePattern(block, num_instances, spacing)
            duration = Timer - start_time
            theSession.UpdateManager.AddToDeleteList(feature_pattern)
        ElseIf type = "FACE" Then
            Dim face_pattern As NXOpen.Features.PatternFaceFeature = makeFacePattern(block, num_instances, spacing)
            duration = Timer - start_time
            theSession.UpdateManager.AddToDeleteList(face_pattern)
        ElseIf type = "GEO" Then 
            Dim geo_pattern As NXOpen.Features.PatternGeometry = makeGeoPattern(block, num_instances, spacing)
            duration = Timer - start_time
            theSession.UpdateManager.AddToDeleteList(geo_pattern)
        Else 
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, "Incorrect input (" & type & ") to runTest function")
        End If

        If debug_mode Then
            Guide.InfoWriteLine(type & " Pattern elapsed time (" & num_instances & "): " & CStr(duration))
        End If

        return duration
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeFeaturePattern
    'Makes Feature Pattern from block
    '------------------------------------------------------------------------------
    Private Function makeFeaturePattern(block As NXOpen.Features.Block, num_instances as String, spacing as String) As NXOpen.Features.PatternFeature
        Try
            Dim workPart As NXOpen.Part = theSession.Parts.Work
            Dim builder As NXOpen.Features.PatternFeatureBuilder

            builder = workPart.Features.CreatePatternFeatureBuilder(Nothing)
            builder.FeatureList.Add(block)
            builder.PatternService.RectangularDefinition.XSpacing.NCopies.SetFormula(num_instances)
            builder.PatternService.RectangularDefinition.XSpacing.PitchDistance.SetFormula(spacing)
            builder.PatternService.RectangularDefinition.XDirection = makeDirection
            
            return builder.Commit()

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeFacePattern
    'Makes Face Pattern from block
    '------------------------------------------------------------------------------
    Private Function makeFacePattern(block As NXOpen.Features.Block, num_instances as String, spacing as String) As NXOpen.Features.PatternFaceFeature
        Try
            Dim workPart As NXOpen.Part = theSession.Parts.Work
            Dim builder As NXOpen.Features.PatternFaceFeatureBuilder
            builder = workPart.Features.CreatePatternFaceFeatureBuilder(Nothing)

            Dim faceFeatureRule As NXOpen.FaceFeatureRule = workPart.ScRuleFactory.CreateRuleFaceFeature({block})
            builder.FaceCollector.ReplaceRules({faceFeatureRule}, False)

            builder.PatternDefinition.RectangularDefinition.XDirection = makeDirection
            builder.PatternDefinition.RectangularDefinition.XSpacing.NCopies.SetFormula(num_instances)
            builder.PatternDefinition.RectangularDefinition.XSpacing.PitchDistance.SetFormula(spacing)
                        
            return builder.Commit()

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeGeoPattern
    'Makes a Geometry Pattern from block
    '------------------------------------------------------------------------------
    Private Function makeGeoPattern(block As NXOpen.Features.Block, num_instances as String, spacing as String) As NXOpen.Features.PatternGeometry
        Try
            Dim workPart As NXOpen.Part = theSession.Parts.Work
            Dim builder As NXOpen.Features.PatternGeometryBuilder
            builder = workPart.Features.CreatePatternGeometryBuilder(Nothing)

            Dim scCollector As NXOpen.ScCollector = workPart.ScCollectors.CreateCollector()
            Dim faceDumbRule as NXOpen.FaceDumbRule = workPart.ScRuleFactory.CreateRuleFaceDumb(block.getFaces())
            scCollector.ReplaceRules({faceDumbRule}, False)
            builder.GeometryToPattern.Add(scCollector)

            builder.PatternService.RectangularDefinition.XDirection = makeDirection
            builder.PatternService.RectangularDefinition.XSpacing.NCopies.SetFormula(num_instances)
            builder.PatternService.RectangularDefinition.XSpacing.PitchDistance.SetFormula(spacing)

            Return builder.Commit()

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: makeDirection
    'Makes and returns a direction from a vector
    '------------------------------------------------------------------------------
    Private Function makeDirection() As NXOpen.Direction
        Dim workPart As NXOpen.Part = theSession.Parts.Work
        Dim origin As New Point3d(0.0, 0.0, 0.0)
        Dim vector As New Vector3d(1.0, 0.0, 0.0)
        return workPart.Directions.CreateDirection(origin, vector, NXOpen.SmartObject.UpdateOption.WithinModeling)
    End Function
    
    '------------------------------------------------------------------------------
    'Function Name: updateFaceRules
    'Updates the face rules based on selection criteria
    '------------------------------------------------------------------------------
    Private Function updateFaceRules() 
        Try
            Dim faceSelect = CType(theDialog.TopBlock.FindBlock("face_select0"), NXOpen.BlockStyler.FaceCollector) 
            If select_type.ValueAsString = "Feature(s)" Then
                faceSelect.FaceRules = FaceRules_FeatureFaces
                faceSelect.LabelString = "Select Feature Faces"
            Else
                faceSelect.FaceRules = FaceRules_SingleFace
                faceSelect.LabelString = "Select Faces"
            End If

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: getObjectCount
    'Counts the number of faces and edges in the selection
    '----------------------------------------------------------------------------
    Private Function getObjectCount()
        Try
            Dim faces() As NXOpen.TaggedObject, total_faces As Integer, this_face as NXOpen.Face
            faces = face_select0.GetSelectedObjects()
            total_faces = UBound(faces) - LBound(faces) + 1

            Dim total_edges As Integer = 0, edges() as NXOpen.Edge, num_edges As Integer
            For Each this_face in faces
                edges = this_face.getEdges()
                num_edges = UBound(edges) - LBound(edges) + 1
                total_edges += num_edges
                Next this_face

            obj_count = total_edges + total_faces

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: updateTimeLabels
    'Updates labels with the estimated time to complete each pattern
    '------------------------------------------------------------------------------
    Private Function updateTimeLabels()
        Try
            If obj_count = 0 Then
                feature_time.Label = "None Selected"
                face_time.Label = "None Selected "
                geo_time.Label = "None Selected"
            Else
                feature_time.Label = formatTime(feature_scale * obj_count * num_instances.Value + feature_offset)
                face_time.Label = formatTime(face_scale * obj_count * num_instances.Value + face_offset)
                geo_time.Label = formatTime(geo_scale * obj_count * num_instances.Value + geo_offset)
            End If

        Catch ex As Exception
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function

    '------------------------------------------------------------------------------
    'Function Name: formatTime
    'Formats the time with a uniform standard
    '------------------------------------------------------------------------------
    Private Function formatTime(time as Decimal)
        return Formatnumber(time, 2, True, False, True)
    End Function

End Class
